defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog
  
run:
  dir: logs/${datamodule.name}_${model.params_model.name}

sweep:
  dir: logs/multiruns/${now:%Y-%m-%d}/${now:%H-%M-%S}
  subdir: ${hydra.job.num}_${hydra.job.id}