_target_: model_interface.SingleScaleModule
params_model:
  name: ESPCN
  in_channels: 1
  upscale_factor: 4
  width: 1
  save_dir: ${hydra:run.dir}
params_optim: ${optim}
params_scheduler: ${scheduler}