_target_: model_interface.SingleScaleModule
params_model:
  name: WDSR
  in_channels: 1
  out_channels: 1
  hidden_channels: 32
  n_res_blocks: 18
  upscale_factor: 4
  save_dir: ${hydra:run.dir}
params_optim: ${optim}
params_scheduler: ${scheduler}