defaults:
  - _self_
  - hydra: default
  - datamodule: vorticity_Re_16000
  - model: HiNOTE
  - optim: default
  - scheduler: default
  - callback: default
  - logger: wandb
  - trainer: default

seed: 3407